name: build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: build .app bundle
    runs-on: macos-latest

    steps:
      - name: repo check
        uses: actions/checkout@v4

      - name: python setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: build app
        run: python setup.py py2app

      - name: zip
        run: |
          cd dist
          zip -r KoroneStrap.zip KoroneStrap.app

      - name: upload build
        uses: actions/upload-artifact@v4
        with:
          name: koronestrap macos build
          path: dist/KoroneStrap.zip